set search_path to login_app_db;


INSERT INTO PERMISSIONS(AUTHORITY) VALUES ('LOGGED_USER_PERMISSION');

INSERT INTO permission_group_label(NAME) values ('LOGGED_USER');


INSERT INTO PERMISSION_GROUP(NAME, FK_AUTHORITY) VALUES ('LOGGED_USER', 'LOGGED_USER_PERMISSION');


INSERT INTO USERS_AUTH_DETAILS( USERNAME, HASHED_PASSWORD, NAME, SURNAME, LAST_PASSWORD_CHANGE_DATE, ISENABLED, 
				ISACCOUNTNONEXPIRED, ISACCOUNTNONLOCKED, ISCREDENTIALSNONEXPIRED, 
				permission_group_name)
 VALUES ('admin','$2a$10$0.ZOiHKGV4PPu1a6NERS3.lSw1Prko7hQEGFOrwvvfkqbYottMa/i',
 'Mario', 'Rossi', CURRENT_TIMESTAMP at time zone 'utc', true, true, true, true, 'LOGGED_USER');	
       
 
 
/*inseriamo i permessi dell'utente superuser*/
INSERT INTO AUTHORITIES( FK_ID_USERS_AUTH_DETAILS, AUTHORITY)  
select id as FK_ID_USERS_AUTH_DETAILS, 'LOGGED_USER_PERMISSION' from USERS_AUTH_DETAILS where 
	USERNAME='admin';
